language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 
script:
  - wasm-pack test --headless --chrome --release